---
title: "Expansion 3G plot"
author: Casey Breen
---

Summary: Create figure with 3g expansion in Nigeria 

```{r}
## Library packages 
library(here)
source(here("code", "helpers.R"))

## Birth panel 
mobile_coverage <- read_csv( here("data", "ng_adm0_coverage.csv"))

## birth panel 
birth_panel <- read_csv(here("data", "birth_panel.csv"))
```

## create plot 

```{r}
## Reshape data 
mobile_coverage_long <- mobile_coverage %>% 
  pivot_longer(-share_type) %>% 
  filter(name != "...1") %>% 
  mutate(year = sub('.*(\\d{4}).*', '\\1', name)) %>% 
  mutate(type = case_when(
    share_type == "pop_share" ~ "Population",
    share_type == "area_share" ~ "Land Area"
  )) %>% 
  mutate(year = as.numeric(year))
```


## Visualize 

```{r}
## Visualize plot 
expansion_3g_plot <- mobile_coverage_long %>% 
  filter(year %in% 2010:2018) %>% 
  mutate(label = if_else(year == max(year), as.character(type), NA_character_)) %>%
  ggplot(aes(x = year, y = value * 100, color = type, fill = type, shape = type)) + 
  geom_line() + 
  geom_point(size = 3, stroke = 1, fill = "white") +
  geom_text(aes(label = round(value * 100, 0)), vjust = -1.5, size = 4) +
  geom_text_repel(aes(label = label),
                  nudge_x = .85,
                  na.rm = TRUE,
                  segment.color = NA) + 
  cowplot::theme_cowplot() +
  scale_x_continuous(breaks = 2010:2018) +
  scale_color_manual(values = c("Population" = "darkblue", "Land Area" = "#CC6600")) +
  scale_fill_manual(values = c("Population" = "darkblue", "Land Area" = "#CC6600")) +
  scale_shape_manual(values = c("Population" = 21, "Land Area" = 23)) +
  labs(x = "Year", y = "Coverage (%)", color = NULL, fill = NULL, shape = NULL) +
  theme(legend.position = "none") +
  ylim(0, 66) + 
  theme(axis.title.y = element_text(face = "bold", colour = "black"),
        axis.title.x = element_text(face = "bold", colour = "black"))

# Save plot
ggsave(plot = expansion_3g_plot,
       filename = here("figures", "fig1_expansion_3g_plot.png"),
       height = 4, width = 7.3, bg = "white")
```

```{r}
## Restrict to 2018
birth_panel_filtered <- birth_panel %>%
  filter(year %in% 2018)

## mobile phone use 
mobile_phone_df <- birth_panel_filtered %>% 
  mutate(pop_3g_pctile = ntile(pop_share_covered_3g, 10)) %>% 
  group_by(pop_3g_pctile) %>% 
  summarize(value = mean(v169a, na.rm = TRUE)) %>% 
  mutate(outcome = "Owns Mobile Phone")

## internet use 
mobile_internet_df <-  birth_panel_filtered %>% 
  mutate(pop_3g_pctile = ntile(pop_share_covered_3g, 10)) %>% 
  mutate(used_internet = case_when(
    v171a == 1 | v171a == 2 ~ 1,
    TRUE ~ 0
  )) %>% 
  group_by(pop_3g_pctile) %>% 
  summarize(value = mean(used_internet, na.rm = TRUE)) %>% 
  mutate(outcome = "Used Internet")

## combine dfs 
df_for_plot <- bind_rows(mobile_phone_df, mobile_internet_df)

## create plot 
internet_use_plot <- df_for_plot %>% 
  group_by(outcome) %>% 
  mutate(label = if_else(pop_3g_pctile == 10, 
                         as.character(outcome), NA_character_)) %>% 
  ungroup() %>% 
  ggplot(aes(x = pop_3g_pctile, y = value*100 , color = outcome, shape = outcome)) + 
  geom_line() + 
  geom_point(size = 3, stroke = 1, fill = "white") +
  scale_color_manual(values = c("Used Internet" = "darkred", "Owns Mobile Phone" = "darkblue")) +
  scale_fill_manual(values = c("Used Internet" = "darkred", "Owns Mobile Phone" = "darkblue")) +
  scale_shape_manual(values = c("Used Internet" = 21, "Owns Mobile Phone" = 23)) +
  geom_text_repel(aes(label = label),
                  nudge_x = .45,
                  nudge_y = .06,
                  na.rm = TRUE,
                  segment.color = NA) + 
  cowplot::theme_cowplot() +
  scale_x_continuous(breaks = 1:10, limits = c(1, 10.5)) +
  ylim(0, 100) +
  labs(y = "Adoption (%)",
       x = "Mobile Internet Coverage (Decile)") +
  theme(legend.position = "none",
        axis.title.y = element_text(face = "bold", colour = "black"),
        axis.title.x = element_text(face = "bold", colour = "black"))

# Save plot
ggsave(plot = internet_use_plot,
       filename = here("figures", "appendix_3g_individual_use.png"),
       height = 4, width = 7.3, bg = "white")
```



