---
title: "DHS Fertility Adjusted"
author: Casey Breen
---

Summary: Estimate DHS fertility rates by 3G coverage (above/below 90%) and mobile phone ownership.  


```{r}
library(here)
source(here("code", "helpers.R"))
```


```{r}
## Individual-level recode 
dhs_women_recode <- haven::read_dta(here("data", "NGIR7BFL.DTA"))

# Cluster-level coverage
coverage_data_cluster <- read_csv(here("data", "coverage_indicators_allyears.csv")) %>%
  filter(source == "gsma", dhsyear %in% c(2018), dhscc == "NG") %>%
  mutate(v000 =  "NG7") %>% 
  filter(year == 2018) %>% 
  clean_names()

# Join microdata with 3G coverage data 
ng_2018_women <- dhs_women_recode %>% 
  left_join(coverage_data_cluster, by = c("v000", "v001"))

```

```{r}
## create new dummy var 
ng_2018_women <- ng_2018_women %>% 
  mutate(dummy_pop_share_covered_3g_above_50 = case_when(
    pop_share_covered_3g > 0.9 ~ 1,
    TRUE ~ 0
  ))

## Nigeria 2018 files 
ng_2018_women <- ng_2018_women %>% 
  filter(!is.na(pop_share_covered_3g)) %>% 
  mutate(phone_coverage = case_when(
    v169a == 0 & dummy_pop_share_covered_3g_above_50 == 0 ~ "No phone, no 3g",
    v169a == 0 & dummy_pop_share_covered_3g_above_50 == 1 ~ "No phone, 3g",
    v169a == 1 & dummy_pop_share_covered_3g_above_50 == 0 ~ "Phone, no 3g",
    v169a == 1 & dummy_pop_share_covered_3g_above_50 == 1 ~ "Phone, 3g"
  ))


(cluster_TFR <- fert(ng_2018_women, Indicator="tfr", JK="Yes", Class = "phone_coverage"))

# Convert 'TFR' and 'SE' columns to numeric (in case they are characters)
cluster_TFR$TFR <- as.numeric(cluster_TFR$TFR)
cluster_TFR$SE <- as.numeric(cluster_TFR$SE)

cluster_TFR <- cluster_TFR %>% 
  mutate(phone = case_when(
    Class %in% c("Phone, 3g", "Phone, no 3g") ~ "Own mobile phone",
    Class %in% c("No phone, 3g", "No phone, no 3g") ~ "No mobile phone",
  )) %>% 
  mutate(three_g = case_when(
    Class %in% c("Phone, 3g", "No phone, 3g") ~ "3G+ Coverage",
    Class %in% c("Phone, no 3g", "No phone, no 3g") ~ "No 3G",
  ))

# Plot the data
nigeria_tfr_fig <- ggplot(cluster_TFR, aes(x = reorder(three_g, TFR), y = TFR, fill = phone)) +
  geom_bar(stat = "identity", alpha = 0.3, color = "black", position = position_dodge(.9)) +  # Bar chart for TFR
  geom_errorbar(aes(ymin = TFR - SE, ymax = TFR + SE), width = 0.2, position = position_dodge(.9)) +  # Error bars for SE
  labs(
    title = "",
    x = "",
    y = "Total Fertility Rate (TFR)",
    fill = ""
  ) +
  ggsci::scale_fill_lancet() + 
  geom_text(aes(y = TFR + SE + 0.4, label = round(TFR, 2)), position = position_dodge(.9)) + 
  cowplot::theme_cowplot() +
    theme_demography() + 
  theme(legend.position = "bottom") + 
  theme(axis.text.x = element_text(face = "bold", colour = "black"),
        axis.title.y = element_text(face = "bold", colour = "black"))

ggsave(nigeria_tfr_fig, filename = here("figures", "nigeria_tfr_plot.png"), width = 6, height = 4, bg = "white")
```


