---
title: "Individual Predictions"
author: Casey Breen
---

Summary: fit two-way-fixed-effects models (TWFE) estimating causal effect of mobile expansion on fertility. 

DROP the restriction to only 0-3G and no-migration assumption. 

```{r}
## library packages 
library(here)
source(here("code", "helpers.R"))

## birth panel 
birth_panel <- read_csv(here("data", "birth_panel.csv"))
```

```{r}
## Filter to pop share covered is 0 
birth_panel_filtered <- birth_panel %>%
  filter(year == 2010, pop_share_covered_3g == 0) %>%
  distinct(v001) %>%
  inner_join(birth_panel, by = "v001") 

birth_panel_filtered <- birth_panel_filtered %>% 
  mutate(islam = case_when(
    v130 == 3 ~ 1,
    TRUE ~ 0)) 

## birth panel filtered 
birth_panel_filtered <- birth_panel_filtered %>%
  arrange(caseid, year) %>%
  group_by(caseid) %>%
  mutate(
    pop_share_covered_3g_lag1 = lag(pop_share_covered_3g, n = 1),
    pop_share_covered_2g_lag1 = lag(pop_share_covered_2g, n = 1),
    birth_lag1 = lag(birth, n = 1)
  ) %>% ungroup()

## restrict to people who lived in same house during window 
birth_panel_filtered <- birth_panel_filtered %>% 
  filter(year %in% 2010:2018) %>% 
  filter(v104 > 5) ## number of years in the same house 

## birth panel filtered 
birth_panel_filtered <- birth_panel_filtered %>%
  mutate(
    pop_share_covered_3g_lag1 = case_when(
      is.na(pop_share_covered_3g_lag1) ~ 0,
      TRUE ~ pop_share_covered_3g_lag1
    ),
    pop_share_covered_2g_lag1 = case_when(
      is.na(pop_share_covered_2g_lag1) ~ 0,
      TRUE ~ pop_share_covered_2g_lag1
    )
  )

birth_panel_filtered <- birth_panel_filtered %>% 
  mutate(early_birth = case_when(
    births_2010_2011 >= 1 ~ 1,
    TRUE ~ 0)) %>% 
  mutate(year_X_early_birth = paste0(year, "_", early_birth))
```


```{r}
# Model 1: No fixed effects or controls
lpm_model1 <- feols(
  birth ~ pop_share_covered_3g_lag1,
  data = birth_panel_filtered,
  cluster = ~v001)

# Model 2: Cluster, year, age, and parity fixed effects
lpm_model2 <- feols( 
  birth ~ pop_share_covered_3g_lag1 + pop_share_covered_2g_lag1 +      ## mobile coverage 
    num_prev_children_pre_window,
  fixef = c("v012", "v001", "year", "year_X_early_birth"),
  data = birth_panel_filtered,
  cluster = ~v001)

# Model 3: Add individual controls
lpm_model3 <- feols(
  birth ~ pop_share_covered_3g_lag1 + pop_share_covered_2g_lag1 +     ## mobile coverage 
    num_prev_children_pre_window +  
    v190 +    ## wealth quantile
    v714 +    ## currently working
    v106 +    ## educ level
    islam +   ## islam variable 
    v158 +    ## frequency of listening to the radio§
    v159,     ## Frequency of watching television     
  fixef = c("v012", "v001", "year", "year_X_early_birth"),
  data = birth_panel_filtered,
  cluster = ~v001)

# Model 4: Add individual controls
lpm_model4 <- feols(
  birth ~ pop_share_covered_3g_lag1 + pop_share_covered_2g_lag1 +      ## mobile coverage 
    num_prev_children_pre_window + 
    nl_mean_wght_v_i + gdp_wght  + temp_mean + rain_mean,  ## time varying covariates
  fixef = c("v012", "v001", "year", "year_X_early_birth"),
  data = birth_panel_filtered,
  cluster = ~v001)

# Model 5: Add individual controls
lpm_model5 <- feols(
  birth ~ pop_share_covered_3g_lag1 + pop_share_covered_2g_lag1 +      ## mobile coverage 
    num_prev_children_pre_window  +      ## parity controls (births prior to window, sum births in window at time t-1) 
    v190 +    ## wealth quantile
    v714 +    ## currently working
    v106 +    ## educ level
    islam +   ## Islam variable 
    v158 +    ## frequency of listening to the radio
    v159 +    ## Frequency of watching television 
    nl_mean_wght_v_i + gdp_wght  + temp_mean + rain_mean,  ## time varying covariates
  fixef = c("v012", "v001", "year", "year_X_early_birth"), ## age, cluster, year FEs 
  data = birth_panel_filtered,
  cluster = ~v001)

# Model 6: LPM with individual (caseid) FE, cluster FE, year, age, parity
lpm_model6 <- feols(
  birth ~ pop_share_covered_3g_lag1 + pop_share_covered_2g_lag1  + ## mobile coverage 
    nl_mean_wght_v_i + gdp_wght  + temp_mean + rain_mean,  ## time varying covariates
  fixef = c("caseid", "year", "year_X_early_birth"),
  data = birth_panel_filtered,
  cluster = ~v001
) 


# Extract and label model coefficients
coef_model1 <- broom::tidy(lpm_model1, conf.int = TRUE, conf.level = 0.95) %>%
  mutate(model = "No Controls")
coef_model2 <- broom::tidy(lpm_model2, conf.int = TRUE, conf.level = 0.95) %>%
  mutate(model = "Baseline", controls = "No")
coef_model3 <- broom::tidy(lpm_model3, conf.int = TRUE, conf.level = 0.95) %>%
  mutate(model = "Baseline", controls = "Yes")
coef_model4 <- broom::tidy(lpm_model4, conf.int = TRUE, conf.level = 0.95) %>%
  mutate(model = "+ Time-varying Controls", controls = "No")
coef_model5 <- broom::tidy(lpm_model5, conf.int = TRUE, conf.level = 0.95) %>%
  mutate(model = "+ Time-varying Controls", controls = "Yes")
coef_model6 <- broom::tidy(lpm_model6, conf.int = TRUE, conf.level = 0.95) %>%
  mutate(model = "+ Time-varying Controls + Mother FEs", controls = "Yes")


model_df_restricted <- coef_model2 %>% 
  bind_rows(coef_model3) %>% 
  bind_rows(coef_model4) %>% 
  bind_rows(coef_model5) %>% 
  bind_rows(coef_model6) %>% 
  filter(term == "pop_share_covered_3g_lag1")
```







```{r}
## Filter to pop share covered is 0 
birth_panel_filtered <- birth_panel %>%
 # filter(year == 2010, pop_share_covered_3g == 0) %>%
  distinct(v001) %>%
  inner_join(birth_panel, by = "v001") 

birth_panel_filtered <- birth_panel_filtered %>% 
  mutate(islam = case_when(
    v130 == 3 ~ 1,
    TRUE ~ 0)) 

## birth panel filtered 
birth_panel_filtered <- birth_panel_filtered %>%
  arrange(caseid, year) %>%
  group_by(caseid) %>%
  mutate(
    pop_share_covered_3g_lag1 = lag(pop_share_covered_3g, n = 1),
    pop_share_covered_2g_lag1 = lag(pop_share_covered_2g, n = 1),
    birth_lag1 = lag(birth, n = 1)
  ) %>% ungroup()

## restrict to people who lived in same house during window 
birth_panel_filtered <- birth_panel_filtered %>% 
  filter(year %in% 2010:2018) #%>% 
  #filter(v104 > 5) ## number of years in the same house 

## birth panel filtered 
birth_panel_filtered <- birth_panel_filtered %>%
  mutate(
    pop_share_covered_3g_lag1 = case_when(
      is.na(pop_share_covered_3g_lag1) ~ 0,
      TRUE ~ pop_share_covered_3g_lag1
    ),
    pop_share_covered_2g_lag1 = case_when(
      is.na(pop_share_covered_2g_lag1) ~ 0,
      TRUE ~ pop_share_covered_2g_lag1
    )
  )

birth_panel_filtered <- birth_panel_filtered %>% 
  mutate(early_birth = case_when(
    births_2010_2011 >= 1 ~ 1,
    TRUE ~ 0)) %>% 
  mutate(year_X_early_birth = paste0(year, "_", early_birth))
```


```{r}
# Model 1: No fixed effects or controls
lpm_model1 <- feols(
  birth ~ pop_share_covered_3g_lag1,
  data = birth_panel_filtered,
  cluster = ~v001)

# Model 2: Cluster, year, age, and parity fixed effects
lpm_model2 <- feols( 
  birth ~ pop_share_covered_3g_lag1 + pop_share_covered_2g_lag1 +      ## mobile coverage 
    num_prev_children_pre_window,
  fixef = c("v012", "v001", "year", "year_X_early_birth"),
  data = birth_panel_filtered,
  cluster = ~v001)

# Model 3: Add individual controls
lpm_model3 <- feols(
  birth ~ pop_share_covered_3g_lag1 + pop_share_covered_2g_lag1 +     ## mobile coverage 
    num_prev_children_pre_window +  
    v190 +    ## wealth quantile
    v714 +    ## currently working
    v106 +    ## educ level
    islam +   ## islam variable 
    v158 +    ## frequency of listening to the radio§
    v159,     ## Frequency of watching television     
  fixef = c("v012", "v001", "year", "year_X_early_birth"),
  data = birth_panel_filtered,
  cluster = ~v001)

# Model 4: Add individual controls
lpm_model4 <- feols(
  birth ~ pop_share_covered_3g_lag1 + pop_share_covered_2g_lag1 +      ## mobile coverage 
    num_prev_children_pre_window + 
    nl_mean_wght_v_i + gdp_wght  + temp_mean + rain_mean,  ## time varying covariates
  fixef = c("v012", "v001", "year", "year_X_early_birth"),
  data = birth_panel_filtered,
  cluster = ~v001)

# Model 5: Add individual controls
lpm_model5 <- feols(
  birth ~ pop_share_covered_3g_lag1 + pop_share_covered_2g_lag1 +      ## mobile coverage 
    num_prev_children_pre_window  +      ## parity controls (births prior to window, sum births in window at time t-1) 
    v190 +    ## wealth quantile
    v714 +    ## currently working
    v106 +    ## educ level
    islam +   ## Islam variable 
    v158 +    ## frequency of listening to the radio
    v159 +    ## Frequency of watching television 
    nl_mean_wght_v_i + gdp_wght  + temp_mean + rain_mean,  ## time varying covariates
  fixef = c("v012", "v001", "year", "year_X_early_birth"), ## age, cluster, year FEs 
  data = birth_panel_filtered,
  cluster = ~v001)

# Model 6: LPM with individual (caseid) FE, cluster FE, year, age, parity
lpm_model6 <- feols(
  birth ~ pop_share_covered_3g_lag1 + pop_share_covered_2g_lag1  + ## mobile coverage 
    nl_mean_wght_v_i + gdp_wght  + temp_mean + rain_mean,  ## time varying covariates
  fixef = c("caseid", "year", "year_X_early_birth"),
  data = birth_panel_filtered,
  cluster = ~v001
) 


# Extract and label model coefficients
coef_model1 <- broom::tidy(lpm_model1, conf.int = TRUE, conf.level = 0.95) %>%
  mutate(model = "No Controls")
coef_model2 <- broom::tidy(lpm_model2, conf.int = TRUE, conf.level = 0.95) %>%
  mutate(model = "Baseline", controls = "No")
coef_model3 <- broom::tidy(lpm_model3, conf.int = TRUE, conf.level = 0.95) %>%
  mutate(model = "Baseline", controls = "Yes")
coef_model4 <- broom::tidy(lpm_model4, conf.int = TRUE, conf.level = 0.95) %>%
  mutate(model = "+ Time-varying Controls", controls = "No")
coef_model5 <- broom::tidy(lpm_model5, conf.int = TRUE, conf.level = 0.95) %>%
  mutate(model = "+ Time-varying Controls", controls = "Yes")
coef_model6 <- broom::tidy(lpm_model6, conf.int = TRUE, conf.level = 0.95) %>%
  mutate(model = "+ Time-varying Controls + Mother FEs", controls = "Yes")


model_df <- coef_model2 %>% 
  bind_rows(coef_model3) %>% 
  bind_rows(coef_model4) %>% 
  bind_rows(coef_model5) %>% 
  bind_rows(coef_model6) %>% 
  filter(term == "pop_share_covered_3g_lag1")
```





```{r}
## baseline fertility 
baseline = 17

model_df <- model_df %>% 
  mutate(sample = "No Sample Restrictions") %>% 
  bind_rows(model_df_restricted %>% mutate(sample = "Restrictions")) %>% 
  mutate(
    estimate = estimate *100/ baseline,
    std.error = std.error *100/ baseline,
    CI_90_low = estimate - std.error * interval1,
    CI_90_high = estimate + std.error * interval1,
    CI_95_low = estimate - std.error * interval2,
    CI_95_high = estimate + std.error * interval2
  ) %>% 
  mutate(
    model = factor(model, levels = c(
      "Baseline", 
      "+ Time-varying Controls",
      "+ Time-varying Controls + Mother FEs"
    ))
  )

effect_plot <- model_df %>%
  filter(controls == "No" | model == "+ Time-varying Controls + Mother FEs" & controls == "Yes") %>% 
  ggplot(aes(x = model, y = estimate)) +
  geom_vline(xintercept = 0, colour = "gray50", lty = 2) +
  geom_linerange(aes(ymin = CI_90_low, ymax = CI_90_high, color = sample), size = 1.3, position = position_dodge(width = 0.3)) +
  geom_pointrange(aes(ymin = CI_95_low, ymax = CI_95_high, color = sample, shape = model),
                  position = position_dodge(width = 0.3), size = 1.5, stroke = 1.5, fill = "white", linewidth = .8) +
  scale_y_continuous(labels = function(x) x * 100) + 
  scale_shape_manual(values = c("Baseline" = 21, "+ Time-varying Controls" = 22, "+ Time-varying Controls + Mother FEs" = 23)) +  # ◯ and ⬜
  labs(x = "",
    y = "Birth Probability Change (%)",
    color = "Individual-level Controls",
    shape = "Individual-level Controls"
  ) +
  cowplot::theme_cowplot() +
  scale_color_manual(values = cud)+ 
  theme(legend.position = "bottom") + 
  geom_hline(yintercept = 0, color = "grey", linetype = "dashed") + 
  theme_demography() + 
  # scale_x_discrete(expand = expansion(mult = c(02, 0.2))) + 
  theme(
    legend.title=element_blank(),
  axis.text.x = element_text(face = "bold", colour = "black", size = 11)) + 
  annotate("text", x = 0.6, y = 0.005, label = "No 3G Expansion", size = 4, hjust = 0, color = "darkgrey") + 
  guides(shape = "none")

 
# Save plots
ggsave(plot = effect_plot, filename = here("figures", "appendix_effect_plot_no_sample_restrictions.png"),
       bg = "white", height = 4, width = 9)
```

